version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    schedule:
      interval: "monthly"
    # target-branch: dependency-updates
    # labels:
    #   - "npm dependencies"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "monthly"
    # labels:
    #   - "workflow dependencies"
