name: 'Markdown to Output'
description: 'Read a markdown file to action output.'
inputs:
  filepath:  # id of input
    description: 'path to markdown file to be read and parsed'
    required: true
outputs:
  attributes:
    description: 'array of parsed front matter attributes'
  body:
    description: 'main body content of file'

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: printer
  color: green
